config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :roommate_requests

  map.root :controller=> "application", :action=> "index"

  map.oauth_authorize '/sessions/facebook_oauth_new', :controller => 'sessions', :action => 'facebook_oauth_new'
  map.oauth_callback '/sessions/facebook_oauth_callback', :controller => 'sessions', :action => 'facebook_oauth_callback'

  map.resources :residences

  map.resources :chore_associations

  map.resources :chores

  map.add_roommate 'users/:id/add_roommate', :controller => 'users', :action => 'add_roommate'
  map.create_roommate_request 'users/:id/create_roommate_request', :controller => 'users', :action => 'create_roommate_request'
  map.accept_roommate_request 'users/:id/accept_roommate_request', :controller => 'users', :action => 'accept_roommate_request'
  map.deny_roommate_request 'users/:id/deny_roommate_request', :controller => 'users', :action => 'deny_roommate_request'
  map.resources :users
  
  map.resources :bills

  map.resources :bill_associations
  
  map.resources :bill_recurrances

  

  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  has_many :bill_associations
  has_many :users, :through => :bill_associations
  has_one :bill_recurrance
  belongs_to :residence
  
  def validate
    validate_has_users
  end
  
  def validate_has_users
    if self.users.size == 0 then
      self.errors.add_to_base "You must assign at least one person to this bill."
    end
  end
  
  def sorted_users_string
    results = ""
    sorted_users = self.users.sort { |a,b| a.name.downcase <=> b.name.downcase }
    sorted_users.each do |roommate|
      results += (roommate.name + ", ")
    end
    results[0..-3]
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_filter :require_login
  layout 'basic'
  before_filter :require_ownership, :only => [:show, :edit, :update, :destroy]
  
  # GET /bills
  # GET /bills.xml
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.xml
  def show
    @bill = Bill.find(params[:id])

    @billrecurrance = @bill.bill_recurrance

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.xml
  def new
    @bill = Bill.new
    @user = User.find_by_id(session[:user_id])
    @roommates = @user.roommates

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = Bill.find(params[:id])
    @user = User.find_by_id(session[:user_id])
    @roommates = @user.roommates
  end

  # POST /bills
  # POST /bills.xml
  def create
    @bill = Bill.new(params[:bill])
    @bill.bill_recurrance = BillRecurrance.new(:recurrance=>params[:bill_recurrance], :end_date=>Date.civil(params[:end_date][:"date(1i)"].to_i,
                                                                                                      params[:end_date][:"date(2i)"].to_i,
                                                                                                      params[:end_date][:"date(3i)"].to_i))

    respond_to do |format|
      if @bill.save
        format.html { redirect_to(@bill, :notice => 'Bill was successfully created.') }
        format.xml  { render :xml => @bill, :status => :created, :location => @bill }
      else
        @user = User.find_by_id(session[:user_id])
        @roommates = @user.roommates
        format.html { render :action => "new" }
        format.xml  { render :xml => @bill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.xml
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to(@bill, :notice => 'Bill was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.xml
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to(bills_url) }
      format.xml  { head :ok }
    end
  end
  
private

  def require_ownership
    @bill = Bill.find(params[:id])
    unless owns_bill?(@bill)
      flash[:error] = "Invalid bill" 
      redirect_to :action => "index"
    end
  end

  def owns_bill?(bill)
    #bill.users.include?(User.find_by_id(session[:user_id]))
    bill.residence == User.find_by_id(session[:user_id]).residence
  end
  
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<% form_for(@bill) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :amount %><br />
    $ <%= f.text_field :amount %>
  </p>
	<p>
		People<br />
		<%= @user.name %>
		<%= check_box_tag("bill[user_ids][]", @user.id, @bill.users.include?(@user)) %><br />
		<% @roommates.each do |roommate| %>
			<%= roommate.name %>
			<%= check_box_tag("bill[user_ids][]", roommate.id, @bill.users.include?(roommate)) %><br />
		<% end %>
	</p>
  <p>
    <%= f.label "Evenly Split?" %><br />
    <%= f.check_box :is_evenly_split %>
  </p>
  <p>
    <%= f.label "Pay by:" %><br />
    <%= f.datetime_select :deadline %>
  </p>
  <p>
    <%= f.label :Recurring %><br />
    <%= f.check_box :is_recurring %>
  </p>
	<%= f.hidden_field :residence_id, :value => @user.residence.id %>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h1>Listing bills</h1>

<%= stylesheet_link_tag "facebox" %>
<script type="text/javascript" src="javascripts/fastinit.js"></script>
<script type="text/javascript" src="javascripts/tablekit.js"></script>
<script type="text/javascript" src="javascripts/jquery.min.js"></script>
<script type="text/javascript" src="javascripts/facebox.js" ></script>
<script type="text/javascript">
	jQuery.noConflict();
	var $j = jQuery;
</script>
<script type="text/javascript">
  jQuery(document).ready(function($) {
    $('a[rel*=facebox]').facebox({
      loading_image : '/images/loading.gif',
      close_image   : '/images/closelabel.gif'
    }) 
  })
</script>

<table class="sortable" cellpadding="5" cellspacing="0">
	<thead>
	  <tr class = "contentHeader">
	    <th class="nosort">Title</th>
	    <th class="nosort">Amount</th>
	    <th class="nosort">Is evenly split</th>
	    <th class="nosort">Deadline</th>
	    <th class="nosort">Is recurring</th>
	  </tr>
	</thead>

<tbody>
<% @bills.each do |bill| %>
  <tr class = "contentRow">
    <td><%=h bill.title %></td>
    <td><%=h bill.amount %></td>
    <td><%=h bill.is_evenly_split %></td>
    <td><%=h bill.deadline %></td>
    <td><%=h bill.is_recurring %></td>
    <td><%= link_to 'Show', bill %></td>
    <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
    <td><%= link_to 'Destroy', bill, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />

<%= link_to 'New bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New bill</h1>

<% form_for(@bill) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :amount %><br />
    $ <%= f.text_field :amount %>
  </p>
	<p>
		People<br />
		<%= @user.name %>
		<%= check_box_tag("bill[user_ids][]", @user.id, @bill.users.include?(@user)) %><br />
		<% @roommates.each do |roommate| %>
			<%= roommate.name %>
			<%= check_box_tag("bill[user_ids][]", roommate.id, @bill.users.include?(roommate)) %><br />
		<% end %>
	</p>
  <p>
    <%= f.label "Evenly Split?" %><br />
    <%= f.check_box :is_evenly_split %>
  </p>
  <p>
    <%= f.label "Pay by:" %><br />
    <%= f.datetime_select :deadline %>
  </p>
  <p>
    <p>
      <%= f.label "Recurring" %><br />
      <%= f.check_box :is_recurring, :onclick=>"toggleOptions();" %>
    </p>
    <div id="recurringOptions">
    <p>
    Recurrance:
    <%= select_tag "bill_recurrance", "<option>Monthly</option><option>Bimonthly</option>" %>
    </p>
    <p>
    End Date:
    <%= datetime_select('end_date', 'date', :order => [:month, :day, :year]) %>
    </p>
    </div>
  </p>
	<%= f.hidden_field :residence_id, :value => @user.residence.id %>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<script type="text/javascript">

  $(document).ready(function(){
    $('#recurringOptions').hide();
  });

  function toggleOptions(){
    $('#recurringOptions').toggle();
  }

</script>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p>
  <b>Title:</b>
  <%=h @bill.title %>
</p>

<p>
  <b>Amount:</b>
  <%=h @bill.amount %>
</p>

<p>
  <b>Is evenly split:</b>
  <%=h @bill.is_evenly_split %>
</p>

<p>
  <b>Deadline:</b>
  <%=h @bill.deadline %>
</p>

<p>
  <b>Is recurring:</b>
  <%=h @bill.is_recurring %>
</p>
<% if @bill.is_recurring %>
  <p>
    <b>Recurrance: </b> <%= @billrecurrance.recurrance %>
  </p>
  <p>
    <b>End Date: </b> <%= @billrecurrance.end_date %>
  </p>
<% end %>


<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>